### ISSUE TITLE
keep original image size in preview.

### ISSUE THREAD

**Issue by WriterStat** [promosis/file-upload-with-preview#24]
Hi, ran across this and trying it out. Thanks!

Using it for one image to test, 

If I choose a small image height x width the preview displays/fills the entire preview area. This could make it blurry.

I may find this, but thought I'd give a quick ask,

Is there a way to keep the original image size in the preview area? Get the original image dimensions?

Thanks much! Appreciate it.

Didn't see this in the notes.

Best,

**Comment by johndatserakis** [comment]
Hi there - thanks for checking out the project.

I see what you're saying about not forcing an image that's smaller than the image preview pane to stretch to fill it.

Luckily I think the fix for this should be pretty simple. The image is stretching because of the `background-size: cover;` property set on the `.custom-file-container__image-preview`. How about you add the following code to your `.css` stylesheet so it overwrites the repo's style.

```css
.custom-file-container__image-preview {
  background-size: contain;

  /* You may want to add this too because the background of the image-preview container is set to a white color. */
  background-color: #eee; 
}
```

Try that and let me know how it goes.
